name: Run tests then Deploy

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: ./Dockerfile.ci

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build docker images
      run: docker build -t main -f $COMPOSE_FILE .

    - name: Run tests
      run: docker run -e NODE_ENV=development main npm run test:jest -- --verbose

    - name: Start Storybook in background
      run: |
        docker run -d -p 6006:6006 main npm run storybook
        sleep 30

    - name: Run Storybook tests
      run: docker run main npm run test:storybook -- --verbose

  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: [test]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install Vercel CLI
      run: npm install -g vercel

    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: vercel --prod --confirm
